#!/usr/bin/env bash
# Sets nginx to run as nginx user.
service nginx stop 
pkill -9 apache2
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
chmod 755 /etc/nginx/nginx.conf
su nginx -c 'service nginx start'
