#!/usr/bin/env bash
# Installs and configures HAProxy on a load balancing server

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen myservers
    bind 0.0.0.0:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 50613-web-01 100.26.10.202:80 check
    server 50613-web-02 3.85.136.153:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
