#!/usr/bin/env bash
# SSH client configuration must be configured to use the private key ~/.ssh/school
# SSH client configuration must be configured to refuse to authenticate using a password
PasswordAuthentication no
IdentityFile ~/.ssh/school
